//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvCApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class cita
    {
        public string cod_cita { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
        public string Id_paciente { get; set; }
        public string id_medico { get; set; }
        public int valor { get; set; }
        public string diagnostico { get; set; }
        public string Nom_acompanante { get; set; }
        public bool activo { get; set; }
    
        public virtual medico medico { get; set; }
        public virtual paciente paciente { get; set; }
    }
}
